spring:
  application:
    name: api
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/api?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://mini-program:mini-program@localhost:27017/mp
management:
  endpoints:
    web:
      exposure:
        include: health,info #, beans, env, mappings, metrics, jolokia, heapdump, configprops, loggers
  endpoint:
    health:
      show-details: ALWAYS
      #show-details: WHEN_AUTHORIZED
    env:
      keys-to-sanitize: java.vm.name, local.server.port
    jolokia:
      config:
        listenForHttpService: true
        debug: true
swagger:
  enabled: true
  title: 小程序Api
  description:  用于给小程序提供功能后台
  version:  1.0.0
  license:  Apache License, Version 2.0
  licenseUrl:  https://www.apache.org/licenses/LICENSE-2.0.html
  #  termsOfServiceUrl:  https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: 负责人
    email: 1@2.com
  base-package:  com.demo.api
  global-operation-parameters:
    - name: x-authentication-token
      description: 从登陆接口获取，除登录接口外，所有接口请求都需要传入
      modelRef: string
      parameterType: header
      required: false
  ui-config:
    json-editor: true
  global-response-message:
    post:
api:
  #后台filter取token时的请求头
  token-header: x-authentication-token
  #小时制
  token-expire: 12
  #用于加密token的密钥
  token-security-key: asdasdasdsadasdsadasdasdasdasdsadasdasdsa
  #用于校验颁发token的单位
  token-issuer: demo.com
  #用于校验token的单位，不同校验单位的token不通用
  token-audience: api.demo.com
  wechat:
    #请求session的路径
    session-key-url: https://api.weixin.qq.com/sns/jscode2session
    #小程序唯一id
    appid: asdasdasdsad
    #小程序密钥
    secret: asdasdasdasdsadasdasdasdasdsad
    #获取发送模板消息的access-token路径
    access-token-path: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential
    template-title-list-path: https://api.weixin.qq.com/cgi-bin/wxopen/template/library/list
    template-keywords-list-path: https://api.weixin.qq.com/cgi-bin/wxopen/template/library/get
    template-add-path: https://api.weixin.qq.com/cgi-bin/wxopen/template/add
    template-list-path: https://api.weixin.qq.com/cgi-bin/wxopen/template/list
    template-del-path: https://api.weixin.qq.com/cgi-bin/wxopen/template/del
    message-send-by-template-path: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send
  short-message:
    sn: asddddddddddddddddddddddddddd
    pwd: asdasdasdsadsadas
    #短信模板
    verify-code-template: 【公司名】验证码：%验证码%，有效期为5分钟，感谢您的使用。提示：请勿泄露给他人
    #每天每个号码发送短信次数限制
    limit-times: 5
logging:
  level:
    root: info
server:
  port: 80
